apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: masters
      rolearn: arn:aws:iam::85126419650:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::856126419650:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HKVR6GUZ6Z60
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T10:12:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "24161"
  uid: 86739988-56e1-459f-953c-7f50fa684d2d
