apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: masters
      rolearn: arn:aws:iam::85126419650:role/UdacityFlaskDeployCBKubectlRole 
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::85126419650:role/eksctl-eksctl-flask-nodegroup-ng-NodeInstanceRole-1RO686CVKUP8I
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T02:29:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "11815"
  uid: d6c4572b-b359-4991-be81-807309aab7d9
