apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::720672061846:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720672061846:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18WSMMCKEL4TC
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T02:50:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1892"
  uid: 2ca7b7c0-ca94-45d9-8acd-7ee4aec94a75
